chore: do more

diff --git a/.github/actions/migrate-database/action.yml b/.github/actions/migrate-database/action.yml
--- a/.github/actions/migrate-database/action.yml
+++ b/.github/actions/migrate-database/action.yml
@@ -2,8 +2,8 @@ name: Migrate database
 description: Migrates the database
 
 inputs:
-  job-name:
-    description: The name of the Kubernetes job that migrates the database
+  migration-object:
+    description: The path to the migration Kubernetes object
     required: true
   kubeconfig:
     description: The kubeconfig file contents, with newlines replaced with '\n' (use a secret)
@@ -14,9 +14,6 @@ inputs:
   timeout:
     description: The timeout for the job
     default: 600
-  seed:
-    description: If the database should be seeded
-    default: false
 
 runs:
   using: composite
@@ -33,31 +30,21 @@ runs:
       run: |
         echo -e "${{ inputs.kubeconfig }}" > kubeconfig
 
-        job_name="${{ inputs.job-name }}-${DATE}-${TAG}"
-        timeout=${{ inputs.timeout }}
-        while [ $timeout -gt 0 ]; do
-          echo "Waiting for job $job_name ($timeout)..."
-          STATUS=$(kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE \
-            get jobs/$job_name -o json 2>/dev/null | jq '.status.conditions[] | .type' 2>/dev/null)
+        kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE \
+          wait -f "${{ inputs.migration-object }}" --for=condition=complete --timeout=${{ inputs.timeout }} &
+        completion_pid=$!
 
-          if [ "$STATUS" == '"Complete"' ]; then
-            job_result=0
-            break
-          elif [ "$STATUS" == '"Failed"' ]; then
-            job_result=1
-            break
-          fi
+        kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE \
+          wait -f "${{ inputs.migration-object }}" --for=condition=complete --timeout=${{ inputs.timeout }} &
+        failure_pid=$!
 
-          sleep 1
-          timeout=$(( timeout - 1 ))
-        done
+        wait -n $completion_pid $failure_pid
 
-        if [ -z "$job_result" ]; then
-          echo "Job $job_name timed out"
-          exit 2
-        elif [ "$job_result" -eq "1" ]; then
-          echo "Job $job_name failed!"
-          exit 1
+        exit_code=$?
+        if (( $exit_code == 0 )); then
+          echo "Job completed"
+        else
+          echo "Job failed with exit code ${exit_code}, exiting..."
         fi
 
-        echo "Job succeeded"
+        exit $exit_code
