chore: limits

diff --git a/.github/actions/migrate-database/action.yml b/.github/actions/migrate-database/action.yml
--- a/.github/actions/migrate-database/action.yml
+++ b/.github/actions/migrate-database/action.yml
@@ -26,12 +26,14 @@ runs:
       run: |
         echo -e "${{ inputs.kubeconfig }}" > kubeconfig
 
-        JOB_NAME=${{ inputs.job-name }}
-        TIMEOUT=${{ inputs.timeout }}
-        while [ $TIMEOUT -gt 0 ]; do
-          echo "Waiting for job $JOB_NAME ($TIMEOUT)..."
+        job_name=${{ inputs.job-name }}
+        timeout=${{ inputs.timeout }}
+        while [ $timeout -gt 0 ]; do
+          echo "Waiting for job $job_name ($timeout)..."
+          kubectl --kubeconfig kubeconfig --namespace ${{ inputs.namespace }} \
+            get job/$job_name
           STATUS=$(kubectl --kubeconfig kubeconfig --namespace ${{ inputs.namespace }} \
-            get job/$JOB_NAME -o json 2>/dev/null | jq '.status.conditions[] | .type' 2>/dev/null)
+            get job/$job_name -o json 2>/dev/null | jq '.status.conditions[] | .type' 2>/dev/null)
 
           if [ "$STATUS" == '"Complete"' ]; then
             job_result=0
@@ -42,14 +44,14 @@ runs:
           fi
 
           sleep 1
-          TIMEOUT=$((TIMEOUT-1))
+          timeout=$(( timeout - 1 ))
         done
 
         if [ -z "$job_result" ]; then
-          echo "Job $JOB_NAME timed out"
-          exit 1
+          echo "Job $job_name timed out"
+          exit 2
         elif [ "$job_result" -eq "1" ]; then
-          echo "Job $JOB_NAME failed!"
+          echo "Job $job_name failed!"
           exit 1
         fi
 
