chore: more

diff --git a/.github/actions/migrate-database/action.yml b/.github/actions/migrate-database/action.yml
--- a/.github/actions/migrate-database/action.yml
+++ b/.github/actions/migrate-database/action.yml
@@ -31,20 +31,21 @@ runs:
         echo -e "${{ inputs.kubeconfig }}" > kubeconfig
         echo -e "${{ inputs.migration-object }}" > migration_object
 
-        echo "Waiting for job $job_name (timeout: ${{ inputs.timeout }})..."
+        echo "Waiting for job (timeout: ${{ inputs.timeout }})..."
+
         timeout=${{ inputs.timeout }}
         while [ $timeout -gt 0 ]; do
-          status=$(kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE get -f migration_object -o json | jq '.status.conditions[] | .type')
-          echo "$status"
+          status=$(kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE get -f migration_object -o json)
 
-          if [ "$status" = '"Complete"' ]; then
-            echo "Job completed!"
-            exit 0
-          fi
-
-          if [ "$status" = '"Failed"' ]; then
-            echo "Job failed"
-            exit 1
+          if [ -n "$status" ]; then
+            status=$(echo $status | jq -r '.status.conditions[].type')
+            if [ "$status" == "Complete" ]; then
+              echo "Job completed"
+              exit 0
+            elif [ "$status" == "Failed" ]; then
+              echo "Job failed"
+              exit 1
+            fi
           fi
 
           sleep 1
